import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientWrapper from "@/app/ClientWrapper"; 
import { initSocket } from "@/lib/socket";
import { createServer } from "http";
const inter = Inter({ subsets: ["latin"] });

const server = createServer();
initSocket(server);

server.listen(3001,()=>{
  "websocket server running at 3001"
})
export const metadata: Metadata = {
  title: "AMU Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex-col bg-gray-100`}>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
